POOL_SIZE      = 10
MAX_OVERFLOW   = 5
POOL_RECYCLE   = 3600
BCP_DRIVER     = 'mssql'



partners_list = [
    
                 "omop_partner_1",
                 "pcornet_partner_1",

                 
                 
                 ]

harmonized_filed_sizes_dict = {

                            "PATID"               :"64",
                            "ENCOUNTERID"         :"128",
                            "PROVIDERID"          :"64",
                            "VX_PROVIDERID"       :"64",
                            "MEDADMIN_PROVIDERID" :"64",
                            "OBSGEN_PROVIDERID"   :"64",
                            "OBSCLIN_PROVIDERID"  :"64",
                            "RX_PROVIDERID"       :"64",
                            "PROCEDURESID"        :"128",
                            "PRESCRIBINGID"       :"128",
                            
                            }


schemas = {






"template":"""

                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         VARCHAR(200),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,



"DEMOGRAPHIC":"""

                         PATID VARCHAR(128),
                         BIRTH_DATE varchar(8000),
                         BIRTH_TIME varchar(8000),
                         SEX varchar(8000),
                         SEXUAL_ORIENTATION varchar(8000),
                         GENDER_IDENTITY varchar(8000),
                         HISPANIC varchar(8000),
                         RACE varchar(8000),
                         BIOBANK_FLAG varchar(8000),
                         PAT_PREF_LANGUAGE_SPOKEN  varchar(8000) ,
                         RAW_SEX varchar(8000),
                         RAW_SEXUAL_ORIENTATION varchar(8000),
                         RAW_GENDER_IDENTITY varchar(8000),
                         RAW_HISPANIC varchar(8000),
                         RAW_RACE varchar(8000),
                         RAW_PAT_PREF_LANGUAGE_SPOKEN varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50),
                         ZIP_CODE VARCHAR(50)

                        """,

"DISPENSING":"""

                         DISPENSINGID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENR_START_DATE varchar(8000),
                         ENR_END_DATE varchar(8000),
                         CHART varchar(8000),
                         ENR_BASIS varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"ENCOUNTER":"""

                         ENCOUNTERID VARCHAR(128),
                         PATID VARCHAR(128),
                         ADMIT_DATE varchar(256),
                         ADMIT_TIME varchar(256),
                         DISCHARGE_DATE varchar(256),
                         DISCHARGE_TIME varchar(256),
                         PROVIDERID VARCHAR(32),
                         FACILITY_LOCATION varchar(256),
                         ENC_TYPE varchar(256),
                         FACILITYID varchar(256),
                         DISCHARGE_DISPOSITION varchar(256),
                         DISCHARGE_STATUS varchar(256),
                         DRG varchar(256),
                         DRG_TYPE varchar(256),
                         ADMITTING_SOURCE varchar(256),
                         PAYER_TYPE_PRIMARY varchar(256),
                         PAYER_TYPE_SECONDARY varchar(256),
                         FACILITY_TYPE varchar(256),
                         RAW_SITEID varchar(256),
                         RAW_ENC_TYPE varchar(256),
                         RAW_DISCHARGE_DISPOSITION varchar(256),
                         RAW_DISCHARGE_STATUS varchar(256),
                         RAW_DRG_TYPE varchar(256),
                         RAW_ADMITTING_SOURCE varchar(256),
                         RAW_FACILITY_TYPE varchar(256),
                         RAW_PAYER_TYPE_PRIMARY varchar(256),
                         RAW_PAYER_NAME_PRIMARY varchar(256),
                         RAW_PAYER_ID_PRIMARY varchar(256),
                         RAW_PAYER_TYPE_SECONDARY varchar(256),
                         RAW_PAYER_NAME_SECONDARY varchar(256),
                         RAW_PAYER_ID_SECONDARY varchar(256),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"DIAGNOSIS":"""

                         DIAGNOSISID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         ENC_TYPE varchar(256),
                         ADMIT_DATE varchar(8000),
                         PROVIDERID VARCHAR(32),
                         DX varchar(256),
                         DX_TYPE varchar(256),
                         DX_DATE varchar(256),
                         DX_SOURCE varchar(256),
                         DX_ORIGIN varchar(256),
                         PDX varchar(256),
                         DX_POA varchar(256),
                         RAW_DX varchar(256),
                         RAW_DX_TYPE varchar(256),
                         RAW_DX_SOURCE varchar(256),
                         RAW_PDX varchar(256),
                         RAW_DX_POA varchar(256),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"PROCEDURES":"""

                         PROCEDURESID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         ENC_TYPE VARCHAR(50),
                         ADMIT_DATE varchar(8000),
                         PROVIDERID VARCHAR(32),
                         PX_DATE varchar(8000),
                         PX varchar(8000),
                         PX_TYPE varchar(8000),
                         PX_SOURCE varchar(8000),
                         PPX varchar(8000),
                         RAW_PX varchar(8000),
                         RAW_PX_TYPE varchar(8000),
                         RAW_PPX varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"VITAL":"""

                         VITALID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         MEASURE_DATE varchar(8000),
                         MEASURE_TIME varchar(8000),
                         VITAL_SOURCE varchar(8000),
                         HT varchar(8000),
                         WT varchar(8000),
                         DIASTOLIC varchar(8000),
                         SYSTOLIC varchar(8000),
                         ORIGINAL_BMI varchar(8000),
                         BP_POSITION varchar(8000),
                         SMOKING varchar(8000),
                         TOBACCO varchar(8000),
                         TOBACCO_TYPE varchar(8000),
                         RAW_DIASTOLIC varchar(8000),
                         RAW_SYSTOLIC varchar(8000),
                         RAW_BP_POSITION varchar(8000),
                         RAW_SMOKING varchar(8000),
                         RAW_TOBACCO varchar(8000),
                         RAW_TOBACCO_TYPE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"DISPENSING":"""

                         DISPENSINGID VARCHAR(128),
                         PATID VARCHAR(128),
                         PRESCRIBINGID VARCHAR(128),
                         DISPENSE_DATE varchar(8000),
                         NDC varchar(8000),
                         DISPENSE_SOURCE varchar(8000),
                         DISPENSE_SUP varchar(8000),
                         DISPENSE_AMT varchar(8000),
                         DISPENSE_DOSE_DISP varchar(8000),
                         DISPENSE_DOSE_DISP_UNIT varchar(8000),
                         DISPENSE_ROUTE varchar(8000),
                         RAW_NDC varchar(8000),
                         RAW_DISPENSE_DOSE_DISP varchar(8000),
                         RAW_DISPENSE_DOSE_DISP_UNIT varchar(8000),
                         RAW_DISPENSE_ROUTE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"LAB_RESULT_CM":"""

                         LAB_RESULT_CM_ID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         SPECIMEN_SOURCE varchar(8000),
                         LAB_LOINC varchar(8000),
                         LAB_RESULT_SOURCE varchar(8000),
                         LAB_LOINC_SOURCE varchar(8000),
                         PRIORITY varchar(8000),
                         RESULT_LOC varchar(8000),
                         LAB_PX varchar(8000),
                         LAB_PX_TYPE varchar(8000),
                         LAB_ORDER_DATE varchar(8000),
                         SPECIMEN_DATE varchar(8000),
                         SPECIMEN_TIME varchar(8000),
                         RESULT_DATE varchar(8000),
                         RESULT_TIME varchar(8000),
                         RESULT_QUAL varchar(8000),
                         RESULT_SNOMED varchar(8000),
                         RESULT_NUM varchar(8000),
                         RESULT_MODIFIER varchar(8000),
                         RESULT_UNIT varchar(8000),
                         NORM_RANGE_LOW varchar(8000),
                         NORM_MODIFIER_LOW varchar(8000),
                         NORM_RANGE_HIGH varchar(8000),
                         NORM_MODIFIER_HIGH varchar(8000),
                         ABN_IND varchar(8000),
                         RAW_LAB_NAME varchar(8000),
                         RAW_LAB_CODE varchar(8000),
                         RAW_PANEL varchar(8000),
                         RAW_RESULT varchar(8000),
                         RAW_UNIT varchar(8000),
                         RAW_ORDER_DEPT varchar(8000),
                         RAW_FACILITY_CODE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"CONDITION":"""

                         CONDITIONID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         REPORT_DATE varchar(8000),
                         RESOLVE_DATE varchar(8000),
                         ONSET_DATE varchar(8000),
                         CONDITION_STATUS varchar(8000),
                         CONDITION varchar(8000),
                         CONDITION_TYPE varchar(8000),
                         CONDITION_SOURCE varchar(8000),
                         RAW_CONDITION_STATUS varchar(8000),
                         RAW_CONDITION varchar(8000),
                         RAW_CONDITION_TYPE varchar(8000),
                         RAW_CONDITION_SOURCE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"PRO_CM":"""

                         PRO_CM_ID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         PRO_DATE varchar(8000),
                         PRO_TIME varchar(8000),
                         PRO_TYPE varchar(8000),
                         PRO_ITEM_NAME varchar(8000),
                         PRO_ITEM_LOINC varchar(8000),
                         PRO_RESPONSE_TEXT varchar(8000),
                         PRO_RESPONSE_NUM varchar(8000),
                         PRO_METHOD varchar(8000),
                         PRO_MODE varchar(8000),
                         PRO_CAT varchar(8000),
                         PRO_SOURCE varchar(8000),
                         PRO_ITEM_VERSION varchar(8000),
                         PRO_MEASURE_NAME varchar(8000),
                         PRO_MEASURE_SEQ varchar(8000),
                         PRO_MEASURE_SCORE varchar(8000),
                         PRO_MEASURE_THETA varchar(8000),
                         PRO_MEASURE_SCALED_TSCORE varchar(8000),
                         PRO_MEASURE_STANDARD_ERROR varchar(8000),
                         PRO_MEASURE_COUNT_SCORED varchar(8000),
                         PRO_MEASURE_LOINC varchar(8000),
                         PRO_MEASURE_VERSION ARCHAR(500),
                         PRO_ITEM_FULLNAME varchar(8000),
                         PRO_ITEM_TEXT varchar(8000),
                         PRO_MEASURE_FULLNAME varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"PRESCRIBING":"""

                         PRESCRIBINGID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         RX_PROVIDERID VARCHAR(32),
                         RX_ORDER_DATE varchar(8000),
                         RX_ORDER_TIME varchar(8000),
                         RX_START_DATE varchar(8000),
                         RX_END_DATE varchar(8000),
                         RX_DOSE_ORDERED varchar(8000),
                         RX_DOSE_ORDERED_UNIT varchar(8000),
                         RX_QUANTITY varchar(8000),
                         RX_DOSE_FORM varchar(8000),
                         RX_REFILLS varchar(8000),
                         RX_DAYS_SUPPLY varchar(8000),
                         RX_FREQUENCY varchar(8000),
                         RX_PRN_FLAG varchar(8000),
                         RX_ROUTE varchar(8000),
                         RX_BASIS varchar(8000),
                         RXNORM_CUI varchar(8000),
                         RX_SOURCE varchar(8000),
                         RX_DISPENSE_AS_WRITTEN varchar(8000),
                         RAW_RX_MED_NAME varchar(8000),
                         RAW_RX_FREQUENCY varchar(8000),
                         RAW_RXNORM_CUI varchar(8000),
                         RAW_RX_QUANTITY varchar(8000),
                         RAW_RX_NDC varchar(8000),
                         RAW_RX_DOSE_ORDERED varchar(8000),
                         RAW_RX_DOSE_ORDERED_UNIT varchar(8000),
                         RAW_RX_ROUTE varchar(8000),
                         RAW_RX_REFILLS varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"DEATH":"""

                         PATID VARCHAR(128),
                         DEATH_DATE varchar(8000),
                         DEATH_DATE_IMPUTE varchar(8000),
                         DEATH_SOURCE varchar(8000),
                         DEATH_MATCH_CONFIDENCE varchar(8000),
                         updated varchar(8000),
                         source varchar(8000)
                        """,
"DEATH_CAUSE":"""

                         PATID VARCHAR(128),
                         DEATH_CAUSE VARCHAR(8),
                         DEATH_CAUSE_CODE varchar(8000),
                         DEATH_CAUSE_TYPE varchar(8000),
                         DEATH_CAUSE_SOURCE varchar(8000),
                         DEATH_CAUSE_CONFIDENCE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"MED_ADMIN":"""

                         MEDADMINID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         PRESCRIBINGID VARCHAR(128),
                         MEDADMIN_PROVIDERID VARCHAR(32),
                         MEDADMIN_START_DATE varchar(8000),
                         MEDADMIN_START_TIME varchar(8000),
                         MEDADMIN_STOP_DATE varchar(8000),
                         MEDADMIN_STOP_TIME varchar(8000),
                         MEDADMIN_TYPE varchar(8000),
                         MEDADMIN_CODE varchar(8000),
                         MEDADMIN_DOSE_ADMIN varchar(8000),
                         MEDADMIN_DOSE_ADMIN_UNIT varchar(8000),
                         MEDADMIN_ROUTE varchar(8000),
                         MEDADMIN_SOURCE varchar(8000),
                         RAW_MEDADMIN_MED_NAME varchar(8000),
                         RAW_MEDADMIN_CODE varchar(8000),
                         RAW_MEDADMIN_DOSE_ADMIN varchar(8000),
                         RAW_MEDADMIN_DOSE_ADMIN_UNIT varchar(8000),
                         RAW_MEDADMIN_ROUTE varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"PROVIDER":"""

                         PROVIDERID VARCHAR(32),
                         PROVIDER_SEX VARCHAR(50),
                         PROVIDER_SPECIALTY_PRIMARY varchar(8000),
                         PROVIDER_NPI varchar(8000),
                         PROVIDER_NPI_FLAG varchar(8000),
                         RAW_PROVIDER_SPECIALTY_PRIMARY varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"OBS_CLIN":"""

                         OBSCLINID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         OBSCLIN_PROVIDERID VARCHAR(32),
                         OBSCLIN_START_DATE varchar(8000),
                         OBSCLIN_START_TIME varchar(8000),
                         OBSCLIN_STOP_DATE varchar(8000),
                         OBSCLIN_STOP_TIME varchar(8000),
                         OBSCLIN_TYPE varchar(8000),
                         OBSCLIN_CODE varchar(8000),
                         OBSCLIN_RESULT_QUAL varchar(8000),
                         OBSCLIN_RESULT_TEXT VARCHAR(1500),
                         OBSCLIN_RESULT_SNOMED varchar(8000),
                         OBSCLIN_RESULT_NUM varchar(8000),
                         OBSCLIN_RESULT_MODIFIER varchar(8000),
                         OBSCLIN_RESULT_UNIT varchar(8000),
                         OBSCLIN_SOURCE varchar(8000),
                         OBSCLIN_ABN_IND varchar(8000),
                         RAW_OBSCLIN_NAME varchar(8000),
                         RAW_OBSCLIN_CODE varchar(8000),
                         RAW_OBSCLIN_TYPE varchar(8000),
                         RAW_OBSCLIN_RESULT VARCHAR(1500),
                         RAW_OBSCLIN_MODIFIER varchar(8000),
                         RAW_OBSCLIN_UNIT varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"OBS_GEN":"""

                         OBSGENID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         OBSGEN_PROVIDERID VARCHAR(32),
                         OBSGEN_START_DATE varchar(8000),
                         OBSGEN_START_TIME varchar(8000),
                         OBSGEN_STOP_DATE varchar(8000),
                         OBSGEN_STOP_TIME varchar(8000),
                         OBSGEN_TYPE varchar(8000),
                         OBSGEN_CODE varchar(8000),
                         OBSGEN_RESULT_QUAL VARCHAR(1500),
                         OBSGEN_RESULT_TEXT varchar(8000),
                         OBSGEN_RESULT_NUM varchar(8000),
                         OBSGEN_RESULT_MODIFIER varchar(8000),
                         OBSGEN_RESULT_UNIT varchar(8000),
                         OBSGEN_TABLE_MODIFIED varchar(8000),
                         OBSGEN_ID_MODIFIED varchar(8000),
                         OBSGEN_SOURCE varchar(8000),
                         OBSGEN_ABN_IND varchar(8000),
                         RAW_OBSGEN_NAME varchar(8000),
                         RAW_OBSGEN_CODE varchar(8000),
                         RAW_OBSGEN_TYPE varchar(8000),
                         RAW_OBSGEN_RESULT VARCHAR(1500),
                         RAW_OBSGEN_UNIT varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,

"HASH_TOKEN":"""

                         PATID VARCHAR(128),
                         TOKEN_01 VARCHAR(128),
                         TOKEN_02 VARCHAR(128),
                         TOKEN_03 VARCHAR(128),
                         TOKEN_04 VARCHAR(128),
                         TOKEN_05 VARCHAR(128),
                         TOKEN_06 VARCHAR(128),
                         TOKEN_07 VARCHAR(128),
                         TOKEN_08 VARCHAR(128),
                         TOKEN_09 VARCHAR(128),
                         TOKEN_12 VARCHAR(128),
                         TOKEN_14 VARCHAR(128),
                         TOKEN_15 VARCHAR(128),
                         TOKEN_16 VARCHAR(128),
                         TOKEN_17 VARCHAR(128),
                         TOKEN_18 VARCHAR(128),
                         TOKEN_23 VARCHAR(128),
                         TOKEN_24 VARCHAR(128),
                         TOKEN_25 VARCHAR(128),
                         TOKEN_26 VARCHAR(128),
                         TOKEN_29 VARCHAR(128),
                         TOKEN_30 VARCHAR(128),
                         TOKEN_101 VARCHAR(128),
                         TOKEN_102 VARCHAR(128),
                         TOKEN_103 VARCHAR(128),
                         TOKEN_104 VARCHAR(128),
                         TOKEN_105 VARCHAR(128),
                         TOKEN_106 VARCHAR(128),
                         TOKEN_107 VARCHAR(128),
                         TOKEN_108 VARCHAR(128),
                         TOKEN_109 VARCHAR(128),
                         TOKEN_110 VARCHAR(128),
                         TOKEN_111 VARCHAR(128),
                         TOKEN_ENCRYPTION_KEY VARCHAR(128),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"LDS_ADDRESS_HISTORY":"""

                         ADDRESSID VARCHAR(128),
                         PATID VARCHAR(128),
                         ADDRESS_USE varchar(8000),
                         ADDRESS_TYPE varchar(8000),
                         ADDRESS_PREFERRED varchar(8000),
                         ADDRESS_CITY varchar(8000),
                         ADDRESS_STATE varchar(8000),
                         ADDRESS_ZIP5 varchar(8000),
                         ADDRESS_ZIP9 varchar(8000),
                         ADDRESS_COUNTY varchar(8000),
                         ADDRESS_PERIOD_START varchar(8000),
                         ADDRESS_PERIOD_END varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"IMMUNIZATION":"""

                         IMMUNIZATIONID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         PROCEDURESID VARCHAR(128),
                         VX_PROVIDERID VARCHAR(32),
                         VX_RECORD_DATE varchar(8000),
                         VX_ADMIN_DATE varchar(8000),
                         VX_CODE_TYPE varchar(8000),
                         VX_CODE varchar(8000),
                         VX_STATUS varchar(8000),
                         VX_STATUS_REASON varchar(8000),
                         VX_SOURCE varchar(8000),
                         VX_DOSE varchar(8000),
                         VX_DOSE_UNIT varchar(8000),
                         VX_ROUTE varchar(8000),
                         VX_BODY_SITE varchar(8000),
                         VX_MANUFACTURER varchar(8000),
                         VX_LOT_NUM varchar(8000),
                         VX_EXP_DATE varchar(8000),
                         RAW_VX_NAME varchar(8000),
                         RAW_VX_CODE varchar(8000),
                         RAW_VX_CODE_TYPE varchar(8000),
                         RAW_VX_DOSE varchar(8000),
                         RAW_VX_DOSE_UNIT varchar(8000),
                         RAW_VX_ROUTE varchar(8000),
                         RAW_VX_BODY_SITE varchar(8000),
                         RAW_VX_STATUS varchar(8000),
                         RAW_VX_STATUS_REASON varchar(8000),
                         RAW_VX_MANUFACTURER varchar(8000),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"HARVEST":"""

                         NETWORKID VARCHAR(10),
                         NETWORK_NAME VARCHAR(20),
                         DATAMARTID VARCHAR(10),
                         DATAMART_NAME VARCHAR(20),
                         DATAMART_PLATFORM VARCHAR(50),
                         CDM_VERSION VARCHAR(50),
                         DATAMART_CLAIMS VARCHAR(50),
                         DATAMART_EHR VARCHAR(50),
                         TOKEN_ENCRYPTION_KEY VARCHAR(200),
                         BIRTH_DATE_MGMT VARCHAR(50),
                         ENR_START_DATE_MGMT VARCHAR(50),
                         ENR_END_DATE_MGMT VARCHAR(50),
                         ENR_END_DATE_MGMT VARCHAR(50),
                         DISCHARGE_DATE_MGMT VARCHAR(50),
                         DX_DATE_MGMT VARCHAR(50),
                         PX_DATE_MGMT VARCHAR(50),
                         RX_ORDER_DATE_MGMT VARCHAR(50),
                         RX_START_DATE_MGMT VARCHAR(50),
                         RX_END_DATE_MGMT VARCHAR(50),
                         DISPENSE_DATE_MGMT VARCHAR(50),
                         LAB_ORDER_DATE_MGMT VARCHAR(50),
                         SPECIMEN_DATE_MGMT VARCHAR(50),
                         RESULT_DATE_MGMT VARCHAR(50),
                         MEASURE_DATE_MGMT VARCHAR(50),
                         ONSET_DATE_MGMT VARCHAR(50),
                         REPORT_DATE_MGMT VARCHAR(50),
                         RESOLVE_DATE_MGMT VARCHAR(50),
                         PRO_DATE_MGMT VARCHAR(50),
                         DEATH_DATE_MGMT VARCHAR(50),
                         MEDADMIN_START_DATE_MGMT VARCHAR(50),
                         MEDADMIN_STOP_DATE_MGMT VARCHAR(50),
                         OBSCLIN_START_DATE_MGMT VARCHAR(50),
                         OBSCLIN_STOP_DATE_MGMT VARCHAR(50),
                         OBSGEN_START_DATE_MGMT VARCHAR(50),
                         OBSGEN_STOP_DATE_MGMT VARCHAR(50),
                         ADDRESS_PERIOD_START_MGMT VARCHAR(50),
                         ADDRESS_PERIOD_END_MGMT VARCHAR(50),
                         VX_RECORD_DATE_MGMT VARCHAR(50),
                         VX_ADMIN_DATE_MGMT VARCHAR(50),
                         VX_EXP_DATE_MGMT VARCHAR(50),
                         REFRESH_DEMOGRAPHIC_DATE DATE,
                         REFRESH_ENROLLMENT_DATE DATE,
                         REFRESH_ENCOUNTER_DATE DATE,
                         REFRESH_DIAGNOSIS_DATE DATE,
                         REFRESH_PROCEDURES_DATE DATE,
                         REFRESH_VITAL_DATE DATE,
                         REFRESH_DISPENSING_DATE DATE,
                         REFRESH_LAB_RESULT_CM_DATE DATE,
                         REFRESH_CONDITION_DATE DATE,
                         REFRESH_PRO_CM_DATE DATE,
                         REFRESH_PRESCRIBING_DATE DATE,
                         REFRESH_PCORNET_TRIAL_DATE DATE,
                         REFRESH_DEATH_DATE DATE,
                         REFRESH_DEATH_CAUSE_DATE DATE,
                         REFRESH_MED_ADMIN_DATE DATE,
                         REFRESH_OBS_CLIN_DATE DATE,
                         REFRESH_PROVIDER_DATE DATE,
                         REFRESH_OBS_GEN_DATE DATE,
                         REFRESH_HASH_TOKEN_DATE DATE,
                         REFRESH_LDS_ADDRESS_HX_DATE DATE,
                         REFRESH_IMMUNIZATION_DATE DATE,
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,



"LAB_HISTORY":"""

                         LABHISTORYID VARCHAR(128),
                         LAB_LOINC VARCHAR(10),
                         LAB_FACILITYID VARCHAR(64),
                         SEX VARCHAR(50),
                         RACE VARCHAR(50),
                         AGE_MIN_WKS INT,
                         AGE_MAX_WKS INT,
                         RESULT_UNIT VARCHAR(20),
                         NORM_RANGE_LOW VARCHAR(10),
                         NORM_MODIFIER_LOW VARCHAR(50),
                         NORM_RANGE_HIGH VARCHAR(10),
                         NORM_MODIFIER_HIGH VARCHAR(50),
                         PERIOD_START DATE,
                         PERIOD_END DATE,
                         RAW_LAB_NAME VARCHAR(200),
                         RAW_UNIT VARCHAR(200),
                         RAW_RANGE VARCHAR(200),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,

"LAB_RESULT_CM":"""

                         LAB_RESULT_CM_ID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         SPECIMEN_SOURCE VARCHAR(50),
                         LAB_LOINC VARCHAR(10),
                         LAB_RESULT_SOURCE VARCHAR(50),
                         LAB_LOINC_SOURCE VARCHAR(50),
                         PRIORITY VARCHAR(50),
                         RESULT_LOC VARCHAR(50),
                         LAB_PX VARCHAR(11),
                         LAB_PX_TYPE VARCHAR(50),
                         LAB_ORDER_DATE VARCHAR(50),
                         SPECIMEN_DATE VARCHAR(50),
                         SPECIMEN_TIME VARCHAR(5),
                         RESULT_DATE VARCHAR(50),
                         RESULT_TIME VARCHAR(5),
                         RESULT_QUAL VARCHAR(50),
                         RESULT_SNOMED VARCHAR(18),
                         RESULT_NUM FLOAT,
                         RESULT_MODIFIER VARCHAR(50),
                         RESULT_UNIT VARCHAR(25),
                         NORM_RANGE_LOW VARCHAR(50),
                         NORM_MODIFIER_LOW VARCHAR(50),
                         NORM_RANGE_HIGH VARCHAR(50),
                         NORM_MODIFIER_HIGH VARCHAR(50),
                         ABN_IND VARCHAR(50),
                         RAW_LAB_NAME VARCHAR(256),
                         RAW_LAB_CODE VARCHAR(100),
                         RAW_PANEL VARCHAR(300),
                         RAW_RESULT VARCHAR(300),
                         RAW_UNIT VARCHAR(50),
                         RAW_ORDER_DEPT VARCHAR(50),
                         RAW_FACILITY_CODE VARCHAR(50),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"LDS_ADDRESS_HISTORY":"""

                         ADDRESSID VARCHAR(128),
                         PATID VARCHAR(128),
                         ADDRESS_USE VARCHAR(50),
                         ADDRESS_TYPE VARCHAR(50),
                         ADDRESS_PREFERRED VARCHAR(50),
                         ADDRESS_CITY VARCHAR(50),
                         ADDRESS_STATE VARCHAR(50),
                         ADDRESS_ZIP5 VARCHAR(5),
                         ADDRESS_ZIP9 VARCHAR(9),
                         ADDRESS_COUNTY VARCHAR(50),
                         ADDRESS_PERIOD_START DATE,
                         ADDRESS_PERIOD_END DATE,
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
                        
"MED_ADMIN":"""

                         MEDADMINID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         PRESCRIBINGID VARCHAR(128),
                         MEDADMIN_PROVIDERID VARCHAR(32),
                         MEDADMIN_START_DATE VARCHAR(50),
                         MEDADMIN_START_TIME VARCHAR(5),
                         MEDADMIN_STOP_DATE VARCHAR(50),
                         MEDADMIN_STOP_TIME VARCHAR(5),
                         MEDADMIN_TYPE VARCHAR(50),
                         MEDADMIN_CODE VARCHAR(50),
                         MEDADMIN_DOSE_ADMIN FLOAT,
                         MEDADMIN_DOSE_ADMIN_UNIT VARCHAR(25),
                         MEDADMIN_ROUTE VARCHAR(25),
                         MEDADMIN_SOURCE VARCHAR(50),
                         RAW_MEDADMIN_MED_NAME VARCHAR(256),
                         RAW_MEDADMIN_CODE VARCHAR(50),
                         RAW_MEDADMIN_DOSE_ADMIN VARCHAR(50),
                         RAW_MEDADMIN_DOSE_ADMIN_UNIT VARCHAR(50),
                         RAW_MEDADMIN_ROUTE VARCHAR(50),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
               
"OBS_CLIN":"""

                         OBSCLINID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         OBSCLIN_PROVIDERID VARCHAR(32),
                         OBSCLIN_START_DATE DATE,
                         OBSCLIN_START_TIME VARCHAR(5),
                         OBSCLIN_STOP_DATE DATE,
                         OBSCLIN_STOP_TIME VARCHAR(5),
                         OBSCLIN_TYPE VARCHAR(50),
                         OBSCLIN_CODE VARCHAR(50),
                         OBSCLIN_RESULT_QUAL VARCHAR(15),
                         OBSCLIN_RESULT_TEXT VARCHAR(1500),
                         OBSCLIN_RESULT_SNOMED VARCHAR(18),
                         OBSCLIN_RESULT_NUM FLOAT,
                         OBSCLIN_RESULT_MODIFIER VARCHAR(50),
                         OBSCLIN_RESULT_UNIT VARCHAR(25),
                         OBSCLIN_SOURCE VARCHAR(50),
                         OBSCLIN_ABN_IND VARCHAR(50),
                         RAW_OBSCLIN_NAME VARCHAR(200),
                         RAW_OBSCLIN_CODE VARCHAR(200),
                         RAW_OBSCLIN_TYPE VARCHAR(200),
                         RAW_OBSCLIN_RESULT VARCHAR(200),
                         RAW_OBSCLIN_MODIFIER VARCHAR(200),
                         RAW_OBSCLIN_UNIT VARCHAR(200),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"OBS_GEN":"""

                         OBSGENID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         OBSGEN_PROVIDERID VARCHAR(32),
                         OBSGEN_START_DATE DATE,
                         OBSGEN_START_TIME VARCHAR(5),
                         OBSGEN_STOP_DATE DATE,
                         OBSGEN_STOP_TIME VARCHAR(5),
                         OBSGEN_TYPE VARCHAR(50),
                         OBSGEN_CODE VARCHAR(50),
                         OBSGEN_RESULT_QUAL VARCHAR(15),
                         OBSGEN_RESULT_TEXT VARCHAR(300),
                         OBSGEN_RESULT_NUM FLOAT,
                         OBSGEN_RESULT_MODIFIER VARCHAR(50),
                         OBSGEN_RESULT_UNIT VARCHAR(25),
                         OBSGEN_TABLE_MODIFIED VARCHAR(50),
                         OBSGEN_ID_MODIFIED VARCHAR(12),
                         OBSGEN_SOURCE VARCHAR(50),
                         OBSGEN_ABN_IND VARCHAR(50),
                         RAW_OBSGEN_NAME VARCHAR(200),
                         RAW_OBSGEN_CODE VARCHAR(200),
                         RAW_OBSGEN_TYPE VARCHAR(200),
                         RAW_OBSGEN_RESULT VARCHAR(200),
                         RAW_OBSGEN_UNIT VARCHAR(200),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,                                                
"PRO_CM":"""

                         PRO_CM_ID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         PRO_DATE DATE,
                         PRO_TIME VARCHAR(5),
                         PRO_TYPE VARCHAR(50),
                         PRO_ITEM_NAME VARCHAR(10),
                         PRO_ITEM_LOINC VARCHAR(10),
                         PRO_RESPONSE_TEXT VARCHAR(128),
                         PRO_RESPONSE_NUM FLOAT,
                         PRO_METHOD VARCHAR(50),
                         PRO_MODE VARCHAR(50),
                         PRO_CAT VARCHAR(50),
                         PRO_SOURCE VARCHAR(50),
                         PRO_ITEM_VERSION VARCHAR(10),
                         PRO_MEASURE_NAME VARCHAR(50),
                         PRO_MEASURE_SEQ VARCHAR(100),
                         PRO_MEASURE_SCORE FLOAT,
                         PRO_MEASURE_THETA FLOAT,
                         PRO_MEASURE_SCALED_TSCORE FLOAT,
                         PRO_MEASURE_STANDARD_ERROR FLOAT,
                         PRO_MEASURE_COUNT_SCORED FLOAT,
                         PRO_MEASURE_LOINC VARCHAR(10),
                         PRO_MEASURE_VERSION ARCHAR(5),
                         PRO_ITEM_FULLNAME VARCHAR(50),
                         PRO_ITEM_TEXT VARCHAR(350),
                         PRO_MEASURE_FULLNAME VARCHAR(50),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
                        
"PROCEDURES":"""

                         PROCEDURESID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         ENC_TYPE VARCHAR(50),
                         ADMIT_DATE VARCHAR(50),
                         PROVIDERID VARCHAR(32),
                         PX_DATE VARCHAR(50),
                         PX VARCHAR(50),
                         PX_TYPE VARCHAR(50),
                         PX_SOURCE VARCHAR(50),
                         PPX VARCHAR(50),
                         RAW_PX VARCHAR(260),
                         RAW_PX_TYPE VARCHAR(50),
                         RAW_PPX VARCHAR(50),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,                        
"PRESCRIBING":"""

                         PRESCRIBINGID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         RX_PROVIDERID VARCHAR(32),
                         RX_ORDER_DATE VARCHAR(50),
                         RX_ORDER_TIME VARCHAR(50),
                         RX_START_DATE VARCHAR(50),
                         RX_END_DATE VARCHAR(50),
                         RX_DOSE_ORDERED FLOAT,
                         RX_DOSE_ORDERED_UNIT VARCHAR(25),
                         RX_QUANTITY FLOAT,
                         RX_DOSE_FORM VARCHAR(50),
                         RX_REFILLS FLOAT,
                         RX_DAYS_SUPPLY FLOAT,
                         RX_FREQUENCY VARCHAR(50),
                         RX_PRN_FLAG VARCHAR(1),
                         RX_ROUTE VARCHAR(25),
                         RX_BASIS VARCHAR(50),
                         RXNORM_CUI VARCHAR(8),
                         RX_SOURCE VARCHAR(50),
                         RX_DISPENSE_AS_WRITTEN VARCHAR(50),
                         RAW_RX_MED_NAME VARCHAR(300),
                         RAW_RX_FREQUENCY VARCHAR(450),
                         RAW_RXNORM_CUI VARCHAR(50),
                         RAW_RX_QUANTITY VARCHAR(50),
                         RAW_RX_NDC VARCHAR(50),
                         RAW_RX_DOSE_ORDERED VARCHAR(50),
                         RAW_RX_DOSE_ORDERED_UNIT VARCHAR(50),
                         RAW_RX_ROUTE VARCHAR(50),
                         RAW_RX_REFILLS VARCHAR(50),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,
"PROVIDER":"""

                         PROVIDERID VARCHAR(32),
                         PROVIDER_SEX VARCHAR(50),
                         PROVIDER_SPECIALTY_PRIMARY VARCHAR(10),
                         PROVIDER_NPI FLOAT,
                         PROVIDER_NPI_FLAG VARCHAR(1),
                         RAW_PROVIDER_SPECIALTY_PRIMARY VARCHAR(100),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,

 
"VITAL":"""

                         VITALID VARCHAR(128),
                         PATID VARCHAR(128),
                         ENCOUNTERID VARCHAR(128),
                         MEASURE_DATE DATE,
                         MEASURE_TIME VARCHAR(50),
                         VITAL_SOURCE VARCHAR(50),
                         HT FLOAT,
                         WT FLOAT,
                         DIASTOLIC FLOAT,
                         SYSTOLIC FLOAT,
                         ORIGINAL_BMI FLOAT,
                         BP_POSITION VARCHAR(50),
                         SMOKING VARCHAR(50),
                         TOBACCO VARCHAR(50),
                         TOBACCO_TYPE VARCHAR(50),
                         RAW_DIASTOLIC VARCHAR(50),
                         RAW_SYSTOLIC VARCHAR(50),
                         RAW_BP_POSITION VARCHAR(50),
                         RAW_SMOKING VARCHAR(300),
                         RAW_TOBACCO VARCHAR(300),
                         RAW_TOBACCO_TYPE VARCHAR(300),
                         updated VARCHAR(50),
                         source VARCHAR(50)
                        """,                        
}